### ISSUE TITLE
Acl role tables

### ISSUE THREAD

**Issue by edrianhadinata** [euclecio/zf3-acl#1]
do you have the example of ACL tables? because I have some problem Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'MyDB.acl_role' doesn't exist in

**Comment by euclecio** [comment]
Sorry, I had forgotten this repo 

`vendor/bin/doctrine-module orm:schema-tool:create` to create database 
`vendor/bin/doctrine-module data-fixture:import` to import fixture data

The fixture data are in `{Module}/src/Entity/Fixture `

`/module/Acl/src/Entity/Fixture/{LoadPrivilege.php, LoadResource.php, LoadRole.php}`
`/module/User/src/Entity/Fixture/LoadUser.php`

**Comment by damcorishabh** [comment]
> 
> 
> Sorry, I had forgotten this repo
> 
> `vendor/bin/doctrine-module orm:schema-tool:create` to create database
> `vendor/bin/doctrine-module data-fixture:import` to import fixture data
> 
> The fixture data are in `{Module}/src/Entity/Fixture `
> 
> `/module/Acl/src/Entity/Fixture/{LoadPrivilege.php, LoadResource.php, LoadRole.php}`
> `/module/User/src/Entity/Fixture/LoadUser.php`

Could you please elaborate on how to do this as I am not able to understand it?

**Comment by damcorishabh** [comment]
> 
> 
> Sorry, I had forgotten this repo
> 
> `vendor/bin/doctrine-module orm:schema-tool:create` to create database
> `vendor/bin/doctrine-module data-fixture:import` to import fixture data
> 
> The fixture data are in `{Module}/src/Entity/Fixture `
> 
> `/module/Acl/src/Entity/Fixture/{LoadPrivilege.php, LoadResource.php, LoadRole.php}`
> `/module/User/src/Entity/Fixture/LoadUser.php`

Could you please elaborate on this solution?
